import React from "react";



function AboutContentGrid () {

    return (
        
        <div className="aboutcontent-box">
             <p className="content-text1"> Starter is a “starter” theme designed for simplicity and minimalism. It is particularly suitable for personal blogs. It is designed by nrk9819. The figma design file available to download for free 🤩 under CC BY 4.4</p>

            <p  className="content-text2">I plan to implement this theme in a variety of site generators and content management systems. My first priorities are enhance, 11ty, astro and ghost (CMS). In the future, there will also be Hugo, Solidstart, Hono, Deno Fresh, Vitepress and SvelteKit versions. Codes for every implementation will be available on my github.</p>

            <p  className="content-text3">Contents in this site, other than this page and external links are dummy and generated by AI. They don’t serve any purpose but being placeholders. All images are downloaded from Unsplash.</p>
         
          

            

           

        </div>


    );
}


export default AboutContentGrid;